from app.database.connection import database_connection
conn, cursor = database_connection()
sql = """
ALTER TRIGGER [dbo].[TGR_DELETA_REG_FINANC]
ON [dbo].[TB_REG_FINANC]
AFTER DELETE
AS
BEGIN
    DELETE FROM TB_ACOMPANHAMENTO_FINANC WHERE IDREGISTRO IN (SELECT ID_REGISTRO FROM DELETED)
    DELETE FROM TB_HISTORICO_FINANC WHERE IDREGISTRO IN (SELECT ID_REGISTRO FROM DELETED)
    DELETE FROM TB_FLUXO_CAIXA WHERE IDREGISTRO IN (SELECT ID_REGISTRO FROM DELETED)
END
"""
cursor.execute(sql)
conn.commit()
print("Trigger TGR_DELETA_REG_FINANC updated successfully.")
