from app.database.connection import database_connection

sql = """
ALTER TRIGGER [dbo].[TGR_INSERE_ACOMPANHAMENTO]
ON [dbo].[TB_REG_FINANC]
AFTER INSERT
AS
BEGIN
    DECLARE @cursor CURSOR;
    DECLARE 
        @IDREG INT, @DT_COMPRA DATE, @V_TOTAL DECIMAL(10,2), @V_EM_ABERTO DECIMAL(10,2), 
        @V_T_P DECIMAL(10,2), @QTD_PARCELAS_T INT, @QTD_PARCELAS_P INT, 
        @ID_C INT, @ID_F INT, @DT_VENCIMENTO DATE, @V_PARCELA DECIMAL(10,2), 
        @MES_DEB_PARCELA INT, @ANO_DEB_PARCELA INT, @N_PARCELA INT;

    SET @cursor = CURSOR FOR
    SELECT ID_REGISTRO, DATA_GASTO, VALOR, N_PARCELAS, IDCATEGORIA, IDFORMA_PAGAMENTO
    FROM INSERTED;

    OPEN @cursor;
    FETCH NEXT FROM @cursor INTO @IDREG, @DT_COMPRA, @V_TOTAL, @QTD_PARCELAS_T, @ID_C, @ID_F;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @DT_VENCIMENTO = @DT_COMPRA;
        SET @V_EM_ABERTO = @V_TOTAL;
        SET @V_T_P = 0.0;
        SET @QTD_PARCELAS_P = 0;
        SET @N_PARCELA = 1;

        IF @ID_F != 100 -- À VISTA (PIX, DEBITO, DINHEIRO) -> MESMO MÊS
        BEGIN
            SET @MES_DEB_PARCELA = MONTH(@DT_COMPRA);
            SET @ANO_DEB_PARCELA = YEAR(@DT_COMPRA);

            INSERT INTO TB_ACOMPANHAMENTO_FINANC 
            (IDREGISTRO, DT_COMPRA, DT_PAGAMENTO, VALOR_TOTAL, VALOR_PARCELA, VALOR_PENDENTE, QT_PARCELAS, QT_PARCELAS_PENDENTES, IDCATEGORIA)
            VALUES
            (@IDREG, @DT_COMPRA, @DT_COMPRA, @V_TOTAL, @V_TOTAL, @V_T_P, @QTD_PARCELAS_T, @QTD_PARCELAS_P, @ID_C);

            INSERT INTO TB_HISTORICO_FINANC 
            (IDREGISTRO, DT_GASTO, VL_TOTAL, VL_PARCELA, QT_PARCELA, N_PARCELA, MES_DEBITO_PARCELA, ANO_DEBITO_PARCELA)
            VALUES
            (@IDREG, @DT_COMPRA, @V_TOTAL, @V_TOTAL, 1, 1, @MES_DEB_PARCELA, @ANO_DEB_PARCELA);
        END
        ELSE -- CARTÃO DE CRÉDITO -> MÊS SUBSEQUENTE
        BEGIN
            SET @DT_VENCIMENTO = DATEFROMPARTS(YEAR(DATEADD(MONTH, 1, @DT_COMPRA)), MONTH(DATEADD(MONTH, 1, @DT_COMPRA)), 1);
            SET @QTD_PARCELAS_P = @QTD_PARCELAS_T - (DATEDIFF(MONTH, @DT_COMPRA, GETDATE()));
            SET @V_PARCELA = (@V_TOTAL / @QTD_PARCELAS_T);
            SET @V_EM_ABERTO = @V_TOTAL - ((@QTD_PARCELAS_T - @QTD_PARCELAS_P) * @V_PARCELA);

            INSERT INTO TB_ACOMPANHAMENTO_FINANC 
            (IDREGISTRO, DT_COMPRA, DT_PAGAMENTO, VALOR_TOTAL, VALOR_PARCELA, VALOR_PENDENTE, QT_PARCELAS, QT_PARCELAS_PENDENTES, IDCATEGORIA)
            VALUES
            (@IDREG, @DT_COMPRA, @DT_VENCIMENTO, @V_TOTAL, @V_PARCELA, @V_EM_ABERTO, @QTD_PARCELAS_T, @QTD_PARCELAS_P, @ID_C);

            WHILE @N_PARCELA <= @QTD_PARCELAS_T
            BEGIN
                -- AQUI ESTÁ A FIX: Cartão começa no Mês + 1 (N_PARCELA sem o -1)
                SET @MES_DEB_PARCELA = MONTH(DATEADD(MONTH, @N_PARCELA, @DT_COMPRA));
                SET @ANO_DEB_PARCELA = YEAR(DATEADD(MONTH, @N_PARCELA, @DT_COMPRA));

                INSERT INTO TB_HISTORICO_FINANC 
                (IDREGISTRO, DT_GASTO, VL_TOTAL, VL_PARCELA, QT_PARCELA, N_PARCELA, MES_DEBITO_PARCELA, ANO_DEBITO_PARCELA)
                VALUES 
                (@IDREG, @DT_COMPRA, @V_TOTAL, @V_PARCELA, @QTD_PARCELAS_T, @N_PARCELA, @MES_DEB_PARCELA, @ANO_DEB_PARCELA);

                SET @N_PARCELA = @N_PARCELA + 1;
            END;
        END;
        FETCH NEXT FROM @cursor INTO @IDREG, @DT_COMPRA, @V_TOTAL, @QTD_PARCELAS_T, @ID_C, @ID_F;
    END;
    CLOSE @cursor; DEALLOCATE @cursor;
END;
"""

conn, cursor = database_connection()
cursor.execute(sql)
conn.commit()
print("Trigger TGR_INSERE_ACOMPANHAMENTO corrigida com sucesso.")
