import pyodbc
from app.database.connection import database_connection

conn, cursor = database_connection()

query = """
    DECLARE @MES INT = 5;
    DECLARE @ANO INT = 2026;

    DECLARE @VL_ENTRADAS DECIMAL(18,2) = COALESCE((
        SELECT SUM(VALOR) FROM TB_FLUXO_CAIXA 
        WHERE MONTH(DATA_REGISTRO) = @MES AND YEAR(DATA_REGISTRO) = @ANO AND IDCATEGORIA = 800
    ), 0);

    DECLARE @VL_SAIDAS DECIMAL(18,2) = COALESCE((
        SELECT SUM(VALOR) FROM TB_FLUXO_CAIXA 
        WHERE MONTH(DATA_REGISTRO) = @MES AND YEAR(DATA_REGISTRO) = @ANO AND IDCATEGORIA != 800
    ), 0);

    DECLARE @SALDO_ATUAL DECIMAL(18,2) = COALESCE((
        SELECT TOP 1 VALOR_ACUMULADO FROM TB_FLUXO_CAIXA ORDER BY ID_FLUXO DESC
    ), 0);

    DECLARE @CUSTO_MEDIO DECIMAL(18,2) = COALESCE((
        SELECT AVG(TOTAL_MES) FROM (
            SELECT SUM(H.VL_PARCELA) AS TOTAL_MES
            FROM TB_HISTORICO_FINANC H
            JOIN TB_REG_FINANC R ON R.ID_REGISTRO = H.IDREGISTRO
            WHERE R.IDCATEGORIA NOT IN (800, 900)
              AND DATEFROMPARTS(H.ANO_DEBITO_PARCELA, H.MES_DEBITO_PARCELA, 1) >= DATEFROMPARTS(YEAR(GETDATE()), 1, 1)
              AND DATEFROMPARTS(H.ANO_DEBITO_PARCELA, H.MES_DEBITO_PARCELA, 1) < DATEADD(MONTH, 1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1))
            GROUP BY MES_DEBITO_PARCELA, ANO_DEBITO_PARCELA
        ) X
    ), 0);

    SELECT @VL_ENTRADAS AS VL_ENTRADAS, @VL_SAIDAS AS VL_SAIDAS, @CUSTO_MEDIO AS CUSTO_MEDIO, @SALDO_ATUAL AS SALDO_ATUAL;
"""
cursor.execute(query)
print("TEST REWRITE:", cursor.fetchone())
